main/models.py
from mongoengine import signals
from flask import url_for
import os

from application import db
from utilities.common import utc_now_ts as now


class Networks(db.Document):
    fwip = db.StringField(db_field="f", required=True)
    maskbits = db.StringField(db_field="m", required=True)
    gateway = db.StringField(db_field="g", required=True)
    tag = db.StringField(db_field="t", required=True)
    comment = db.StringField(db_field="c", required=True)
    zone = db.StringField(db_field="z", required=True)

class FireWalls(db.Document):
    firewall_ip = db.StringField(db_field="f", required=True, unique=True)
    ha_pair_id = db.StringField(db_field="h", required=True)
    created = db.IntField(db_field="c", default=now())

class Creds(db.Document):
    fwip = db.StringField(db_field="f", required=True, unique=True)
    username = db.StringField(db_field="u", required=True)
    password = db.StringField(db_field="p", required=True)

main/views.py
#!/usr/bin/env python
# Copyright (c) 2020 Hewlett Packard Enterprise Development LP

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# __author__ = "@netwookie"
# __credits__ = ["Rick Kauffman"]
# __license__ = "MIT"
# __maintainer__ = "Rick Kauffman"
# __email__ = "rick.a.kauffman@hpe.com"

# http://pandevice.readthedocs.io/en/latest/reference.html

"""
bulk_subinterfaces.py
=====================

Use bulk operations to create / delete hundreds of firewall interfaces.

NOTE: Please update the hostname and auth credentials variables
      before running.

The purpose of this script is to use and explain both the bulk operations
as it relates to subinterfaces as well as the new function that organizes
objects into vsys.  This script will show how the new bulk operations
correctly handle when subinterface objects are in separate vsys trees.

"""
from flask import Blueprint, render_template, request, redirect, session, url_for, abort
import uuid
import os
from main.models import Networks, FireWalls, Creds
from werkzeug.utils import secure_filename
import datetime
import random
import sys
# Copyright (c) 2017, Palo Alto Networks
from pandevice import device
from pandevice import firewall
from pandevice import network

ALLOWED_EXTENSIONS = set(['csv'])

main_app = Blueprint('main_app', __name__)

@main_app.route('/return_to', methods=('GET', 'POST'))
def return_to():
    for i in Creds.objects:
        fwip=i.fwip
        banner = 'You authenticated using %s credentials' % (fwip)

    return render_template('main/mainx.html', banner=banner)

@main_app.route('/', methods=('GET', 'POST'))
def main():
    '''
    display the login screen
    '''

    return render_template('main/new_main.html')

@main_app.route('/mainx', methods=('GET', 'POST'))
def mainx():
    '''
    capture login info
    '''
    # Get the credentials from the user
    username = request.form.get('username')
    password = request.form.get('password')
    fwip= request.form.get('fwip')

    # Clear creds for storing
    Creds.objects().delete()
    creds = Creds(fwip=fwip,username=username,password=password)
    try:
        creds.save()
    except:
        error = 'ERR002-Failed to save creds to the database'
        return render_template('main/dberror.html')


    # First, let's create the firewall object that we want to modify.
    fw = firewall.Firewall(fwip, username, password)
    banner = 'You authenticated using %s credentials' % (fwip)

    return render_template('main/mainx.html', banner=banner)



# Bulk import from file selector
@main_app.route('/sub_deploy', methods = ['GET', 'POST'])
def sub_deploy():
    firewalls = []
    # get current items
    for i in Networks.objects:
        fwip = i.fwip
        if fwip not in firewalls:
            firewalls.append(fwip)

    return render_template('main/fw_chooser.html', firewalls=firewalls)

# Bulk import from file selector
@main_app.route('/deploy_interface', methods = ['GET', 'POST'])
def deploy_interface():
    fw_deploy= request.form.get('firewall')
    for i in Creds.objects:
        fwip=i.fwip.encode('utf-8')
        username=i.username.encode('utf-8')
        password=i.password.encode('utf-8')
    if fwip == None:
        error = 'ERR2222-No creds in the Creds DB. Log out and login again'
        return render_template('main/dberror.html')

    ints=[]

    # get info from firewall...must have active interfaces
    fw = firewall.Firewall(fwip, username, password)
    interfaces = network.EthernetInterface.refreshall(fw, add=False)
    for eth in interfaces:
        ints.append(eth)

    return render_template('main/interface_chooser.html', interfaces=ints, fwip=fwip)

# Deploy sub interfaces from the database
@main_app.route('/deploy', methods = ['GET', 'POST'])
def deploy():
    # Get the credentials from the user
    selected_fwip = request.form.get('firewall').encode('utf-8')
    interface = request.form.get('interface').encode('utf-8')
    router = request.form.get('router').encode('utf-8')

    if interface == 'none selected':
        error = "ERR2222-Go back you didn't select an interface"
        return render_template('main/gen_error.html', error=error)

    '''
    Handling HA

    # Don't assume either firewall is primary or active.
    # Just start by telling pandevice they are an HA pair
    # and how to connect to them.
    fw = Firewall('10.0.0.1', 'admin', 'password')
    fw.set_ha_peers(Firewall('10.0.0.2', 'admin', 'password'))
    fw.refresh_ha_active()
    # Now, verify the config is synced between the devices.
    # If it's not synced, force config synchronization from active to standby
    if not fw.config_synced():
        fw.synchronize_config()  # blocks until synced or error
    '''
    for i in Creds.objects:
        fwip=i.fwip.encode('utf-8')
        username=i.username.encode('utf-8')
        password=i.password.encode('utf-8')

        if fwip == None:
            error = 'ERR2222-No creds in the Creds DB. Log out and login again'
            return render_template('main/dberror.html')

    # First, let's create the firewall object that we want to modify.
    fw = firewall.Firewall(selected_fwip, username, password)
    # Get vsys
    vsys_list = device.Vsys.refreshall(fw, name_only=True)

    # This works...need to figure out a better way
    vsys = random.choice(vsys_list)

    # Let's make our base interface that we're going to make subinterfaces
    base = network.EthernetInterface(interface, "layer3")
    fw.add(base)
    base.create()
    # Now let's go ahead and make all of our subinterfaces.
    for i in Networks.objects:
        gateway=i.gateway.encode('utf-8')
        tag=i.tag.encode('utf-8')
        comment=i.comment.encode('utf-8')
        zone=i.zone.encode('utf-8')

        # Build subinterface
        name = "{0}.{1}".format(interface, tag)
        sub_intf = network.Layer3Subinterface(name,tag,gateway,comment)
        # Now add the subinterface to that randomly chosen vsys.
        vsys.add(sub_intf)
        vr = sub_intf.set_virtual_router(virtual_router_name=router)
        security_zone = sub_intf.set_zone(zone_name=zone)

    # Creat all subinterfaces at once
    sub_intf.create_similar()
    vsys.add(vr)
    vsys.add(security_zone)
    vr.create()
    security_zone.create()

    return render_template('main/deploy_success.html', fwip=selected_fwip)


# Bulk import from file selector
@main_app.route('/bulk_picker', methods = ['GET', 'POST'])
def bulk_picker():
    return render_template('main/chooser.html')

# Bulk import from file selector
@main_app.route('/bulk', methods = ['GET', 'POST'])
def bulk():
    if request.method == 'POST':
        file = request.files['file']
        # check if the post request has the file part
        if 'file' not in request.files:
            error = 'Missing File Part'
            return render_template('main/chooser.html', error=error)
        # if user does not select file, browser also
        # submit a empty part without filename
        if file.filename == '':
            error = 'No selected file'
            return render_template('main/chooser.html', error=error)

        file.save(os.path.join(file.filename))
        vars = []
        with open(os.path.join(file.filename)) as f:
            line = f.readline().strip('/t')
            check = 0
            while line:
                vars = line.split(',')
                fwip = vars[0]
                # Check to make sure that this firewall has not been uploaded.
                for i in Networks.objects:
                    fw_check=i.fwip
                    if fwip == fw_check and check == 0:
                        error = 'ERR00034, trying to upload duplicate CSV'
                        return render_template('main/dberror.html', error=error)
                # set the check flag
                check = 1
                gateway=vars[1][:-1]+'1'
                junk, maskbits=vars[3].split('/')
                tag=vars[4]
                comment=vars[5]
                zone=vars[6][:-1]

                # Write controller to database
                try:
                    out = Networks(fwip=fwip,gateway=gateway,maskbits=maskbits,tag=tag,comment=comment,zone=zone)
                    out.save()
                except:
                    error = 'ERR001-Failed to save network to the database'
                    return render_template('main/dberror.html')
                line = f.readline().strip('/t')

    return render_template('main/db_uploaded.html')

# Select record for editing
@main_app.route('/show_networks', methods = ['GET'])
def show_networks():
    error = None
    count = 0
    networks = []

    # get current items
    for i in Networks.objects:
        fwip = i.fwip
        maskbits = i.maskbits
        gateway = i.gateway
        tag = i.tag
        comment = i.comment
        zone = i.zone
        out = [fwip,maskbits,gateway,tag,comment,zone]
        networks.append(out)

templates/main/ask_db_drop.html
{% extends 'base.html' %}


{% block title %}Panix Question The User's Behaviour{% endblock %}


{% include 'navbar.html' %}

{% block content %}

 <div class="jumbotron">
				<h3>Are you sure you want to drop the sub interface database?</h3>
				<p class="lead"></p>
        </div>

        <h2>{{error}}</h2>

<div class="container">
    <form action="{{ url_for('main_app.db_drop') }}" method=post>
          <button type="submit" class="btn btn-lg btn-danger btn-block">Danger Will Robinson!</button>

      </form>



</div>
{% endblock %}

templates/main/chooser.html
{% extends 'base.html' %}


{% block title %}Panix File Chooser{% endblock %}


{% include 'navbar.html' %}

{% block content %}

 <div class="jumbotron">
				<h3>Select a CSV file to bulk upload into the database</h3>
				<p class="lead"></p>
        </div>

        <h2>{{error}}</h2>

<div class="container">
    <form action="{{ url_for('main_app.bulk') }}" method=post enctype=multipart/form-data>
        <p><input type=file name=file><br><br>
           <input type=submit value=Upload>
      </form>



</div>
{% endblock %}

templates/main/db_drop.html
{% extends 'base.html' %}


{% block title %}Panix Firewall Automation{% endblock %}


{% include 'navbar.html' %}

{% block content %}

 <div class="jumbotron">
				<h3>Database Dropped!</h3>
				<p class="lead"></p>
        </div>

<div class="container">


<div class="row">

<h2>Notice!!</h2>

{{ fwip }}

  <p> All subinterface information has bee dropped from the database! n</p>
  <form  method="POST" action="{{ url_for('main_app.return_to') }}">

    <br>
    <hr>
    <button type="submit" class="btn btn-lg btn-primary btn-block">Back to Main</button>


</form>
{% endblock %}

templates/main/db_uploaded.html
{% extends 'base.html' %}


{% block title %}Panix Firewall Automation{% endblock %}


{% include 'navbar.html' %}

{% block content %}
<form  method="POST" action="{{ url_for('main_app.return_to') }}">
 <div class="jumbotron">
				<h3>CSV file has been uploaded to the subinterface database!</h3>
				<p class="lead"></p>
        </div>

<div class="container">


<div class="row">

<h2>Notice!!</h2>

{{ fwip }}

  <p> Subinterfaces have been successfully uploded!</p>


    <br>
    <hr>
    <button type="submit" class="btn btn-lg btn-primary btn-block">Back to Main</button>
  

</form>
{% endblock %}

templates/main/dberror.html
{% extends "base.html" %}

{% block title %}Error{% endblock %}

{% block content %}

<form  method="POST" action="{{ url_for('main_app.return_to') }}">
   <div class="jumbotron">
    <h3>Database writting error</h3>
    <h2> Please try again!</h2>
    <p> Use the BACK button or go to the main screen</p>
      {{ error }}
      <hr>
      <button type="submit" class="btn btn-lg btn-primary btn-block">Back to Main</button>

  </div>


{% endblock %}

templates/main/deploy_success.html
{% extends 'base.html' %}


{% block title %}Panix Firewall Automation{% endblock %}


{% include 'navbar.html' %}

{% block content %}

 <div class="jumbotron">
				<h3>Subinterfaces Deployed!</h3>
				<p class="lead"></p>
        </div>

<div class="container">


<div class="row">

<h2>Notice!!</h2>

{{ fwip }}

  <p> Subinterfaces have been successfully deployed! n</p>
  <form  method="POST" action="{{ url_for('main_app.return_to') }}">

    <br>
    <hr>
    <button type="submit" class="btn btn-lg btn-primary btn-block">Back to Main</button>
    <input type="hidden" name=controller value={{ controller }}>

</form>
{% endblock %}

templates/main/fw_chooser.html
{% extends 'base.html' %}


{% block title %}Panix Firewall Chooser{% endblock %}


{% include 'navbar.html' %}

{% block content %}

 <div class="jumbotron">
				<h3>Select a Firewall IP to deploy subinterfaces</h3>
				<p class="lead"></p>
        </div>

        <h2>{{error}}</h2>

<div class="container">
    <form action = "{{ url_for('main_app.deploy_interface') }}" method = "post">
      <select name ="firewall">
                <option value={{fire}}>'none selected'</option>
              {% for fire in firewalls %}
                <option value={{fire}}>{{fire}}</option>
                {% endfor %}

      </select>

      <hr>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Deploy Firewall</button>
      <br>
      </form>



</div>
{% endblock %}

templates/main/gen_error.html
{% extends "base.html" %}

{% block title %}Error{% endblock %}

{% block content %}

<form  method="POST" action="{{ url_for('main_app.return_to') }}">
   <div class="jumbotron">
    <h3>General System Error</h3>
    <h2> Please try again!</h2>
    <p> Use the BACK button or go to the main screen</p>
      {{ error }}
      <hr>
      <button type="submit" class="btn btn-lg btn-primary btn-block">Back to Main</button>

  </div>


{% endblock %}

templates/main/help.html
{% extends "base.html" %}

{% block title %}Help{% endblock %}

{% block content %}


  <form action = "{{ url_for('main_app.return_to') }}" method = "post">
<div class="col-xs-10">
    <h1>Help for Panix</h1>
    <p> Panix help information</p>
    <p>
    <h3> Assumptions </h3>
    <p> You have a Palo Alto Firewall on your network.</p>
    <p> You must have credentials to modify this firewall</p>
    <p> CSV file you want to upload MUST look like this!</p>
    <img src="{{ url_for('static', filename='assets/spreadsheet.png') }}" width="400"  heights="90"/>
    <ol>
        <li>IP address of FW management interface</li>
        <li>IP network for the subinterface...not the vlan gateway address...ends in zero!</li>
        <li>Column "C" not used....don't ask :-)</li>
        <li>Subnet mask bits as shown...full mask with slash followed by bits</li>
        <li>Vlan number</li>
        <li>Comments about the sub interface</li>
        <li>Security Zone</li>
    </ol>
    <p>This app was written to bulk add Layer 3 subinterfaces to a Palo Alto firewall using the
      pandevice python library. <p>
      <b>Current Behavior</b><br>
      <ul>
        <li>You must have a separate CSV file for each firewall or one giant one that contains all the data</li>
        <li>A multisheet excel file will not work</li>
        <li>Upload CSV's into the mongo database</li>
        <li>Deploy firewall subinterfaces one firewall at a time</li>
        <li>If you have trouble logging in go to http://localhost:5001/logout</li>
        </ul>


          <button class="btn btn-lg btn-primary btn-block" type="submit">Back to Main</button>


  </div>

</div>
{% endblock %}

templates/main/interface_chooser.html
{% extends 'base.html' %}


{% block title %}Panix Interface Chooser{% endblock %}


{% include 'navbar.html' %}

{% block content %}

 <div class="jumbotron">
				<h3>Select an Interface deploy subinterfaces</h3>
				<p class="lead"></p>
        </div>



<div class="container">
    <form action = "{{ url_for('main_app.deploy') }}" method = "post">
      <select name ="interface">
                <option>none selected</option>
              {% for i in interfaces %}
                <option value={{i}}>{{i}}</option>
                {% endfor %}

      </select>
      <br><br>
      <br><br>
      <br>
      <p>Enter the Virtual Router: <input type=text  id="router" class="form-control" placeholder="virtual router"  required name="router"></p>
      <input type="hidden" id="fpip_addr" name="firewall" value={{fwip}}><br><br>
      <hr>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Deploy Subnets</button>

      <br>
      </form>



</div>
{% endblock %}

templates/main/main.html
{% extends "base.html" %}

{% block title %}Welcome to Panix{% endblock %}

{% block header %}<link href="{{ url_for('static', filename='css/base.css') }}" rel="stylesheet">{% endblock %}

{% block content %}
    <!-- Main jumbotron for a primary marketing message or call to action -->

      <div class="container">
        <hr>
        <h2>Bison: An application to automate Big Switch Controller functions</h2>
        <p>API integration to Big Switch Networks BSN controller</p>
        <form action = "/init" method = "post">
          <hr>
          <p>BSN IP: <input type=text  id="bsn_host" class="form-control" placeholder="10.1.1.1"  name="bsnip"></p>
          <p>BSN User: <input type=text  id="bsn_user" class="form-control" placeholder="BSN User Id"  name="bsn_user"></p>
          <p>BSN Password: <input type="password" id="bsn_passwd" class="form-control" placeholder="Password" required name="bsn_word"></p>
          <button class="btn btn-primary btn-sm" type="submit">Start Application</button>
          <input type="hidden" name=seed_ip value=''>
          <input type="hidden" name=mask value=''>

        </form>
    </div>

{% endblock %}

templates/main/mainx.html
{% extends "base.html" %}

{% block title %}Welcome to Panix{% endblock %}

{% block header %}<link href="{{ url_for('static', filename='css/base.css') }}" rel="stylesheet">{% endblock %}

{% include "navbar.html" %}

{% block content %}

    <!-- Main jumbotron for a primary marketing message or call to action -->

    {{x}}

      <div class="container">
        <h2>Panix</h2>
        <p>Palo Alto Network Interface eXecutor</p>
        <img src="{{ url_for('static', filename='assets/datacenter2.jpg') }}" width="600"  heights="90"/>

          <h4> {{ banner }} </h4>

        {{ error }}


    </div>


{% endblock %}

templates/main/new_main.html
{% extends "base.html" %}

{% block title %}Welcome to Panix{% endblock %}

{% block header %}<link href="{{ url_for('static', filename='css/base.css') }}" rel="stylesheet">{% endblock %}

{% block content %}
    <!-- Main jumbotron for a primary marketing message or call to action -->

      <div class="container">
        <hr>
        <h2>Panix: Palo Alto Network Interface eXecutor</h2>
        <p>Hundreds of subinterfaces?....Easy!</p>
        <form action = "/mainx" method = "post">
          <hr>
          <p>Firewall IP: <input type=text  id="firewall" class="form-control" placeholder="10.1.1.1"  name="fwip"></p>
          <p>User: <input type=text  id="user" class="form-control" placeholder="User Id"  name="username"></p>
          <p>Password: <input type="password" id="passwd" class="form-control" placeholder="Password" required name="password"></p>
          <hr>
          <button class="btn btn-primary btn-sm" type="submit">Sign In</button>
        </form>
    </div>

{% endblock %}

templates/main/show_networks.html
{% extends 'base.html' %}


{% block title %}Panix{% endblock %}


{% include 'navbar.html' %}

{% block content %}



<div class="container">
    <h3> Panix Networks</h3>
    <form action = "{{ url_for('main_app.return_to') }}" method = "post">
     <p> Networks in the Panix database

    <table class="table table-responsive">
       <thead>
          <tr>
             <th>Firewall IP</th>
             <th>Network Mask</th>
             <th>Comment</th>
             <th>Tag</th>
             <th>Interface IP</th>
             <th>Zone</th>
          </tr>
       </thead>

       <tbody>
              {% for item in networks %}
             <tr>
                <td> {{ item.0 }}</td>
                <td> {{ item.1 }} </td>
                <td> {{ item.4 }}</td>
                <td> {{ item.3 }} </td>
                <td> {{ item.2 }} </td>
                <td> {{ item.5 }} </td>
             </tr>
              {% endfor %}
       </tbody>
    </table>
    <hr>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Back to Main</button>
    <br>
  </form>
  </div>
</div>
{% endblock %}